use_frameworks!

platform :ios, '10.0'

target 'ZDToolBoxObjC_Example' do
  pod 'ZDToolBoxObjC', :subspecs => ['All'], :path => '../'

  target 'ZDToolBoxObjC_Tests' do
    inherit! :search_paths

    
  end
end
